name: "Docker"
on: [push]
jobs:
  run:
    name: "Build and publish Docker image"
    runs-on: "ubuntu-latest"
    steps:
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: myorg/myrepository
          tag_with_ref: true
          tag_with_sha: true
